// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMF.OrderManagementService.Command.Repository.DataContext;

namespace OMF.OrderManagementService.Command.Repository.Migrations
{
    [DbContext(typeof(OrderManagementContext))]
    [Migration("20200526060904_order")]
    partial class order
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OMF.OrderManagementService.Command.Repository.DataContext.TblFoodOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("('')");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Status")
                        .HasColumnName("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TblCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblCustomerID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TblRestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblRestaurantID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.ToTable("tblFoodOrder");
                });

            modelBuilder.Entity("OMF.OrderManagementService.Command.Repository.DataContext.TblFoodOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnName("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TblFoodOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblFoodOrderID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TblMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblMenuID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("TblFoodOrderId");

                    b.ToTable("tblFoodOrderItem");
                });

            modelBuilder.Entity("OMF.OrderManagementService.Command.Repository.DataContext.TblOrderPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("OrderId")
                        .HasColumnName("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .HasColumnName("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnName("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("('')");

                    b.Property<int>("TblCustomerId")
                        .HasColumnName("tblCustomerID")
                        .HasColumnType("int");

                    b.Property<int?>("TblFoodOrderId")
                        .HasColumnType("int");

                    b.Property<int?>("TblTableBookingId1")
                        .HasColumnType("int");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnName("TransactionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TblFoodOrderId");

                    b.HasIndex("TblTableBookingId1");

                    b.ToTable("tblOrderPayment");
                });

            modelBuilder.Entity("OMF.OrderManagementService.Command.Repository.DataContext.TblTableBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("FromDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Status")
                        .HasColumnName("BookingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TblCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblCustomerID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TblRestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblRestaurantID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ToDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.ToTable("tblTableOrder");
                });

            modelBuilder.Entity("OMF.OrderManagementService.Command.Repository.DataContext.TblTableDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TableNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TblTableBookingId")
                        .HasColumnType("int");

                    b.Property<int>("UserCreated")
                        .HasColumnType("int");

                    b.Property<int>("UserModified")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TblTableBookingId");

                    b.ToTable("tblTableOrderMapping");
                });

            modelBuilder.Entity("OMF.OrderManagementService.Command.Repository.DataContext.TblFoodOrderItem", b =>
                {
                    b.HasOne("OMF.OrderManagementService.Command.Repository.DataContext.TblFoodOrder", "TblFoodOrder")
                        .WithMany("TblFoodOrderItem")
                        .HasForeignKey("TblFoodOrderId")
                        .HasConstraintName("FK_tblFoodOrderMapping_tblFoodOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OMF.OrderManagementService.Command.Repository.DataContext.TblOrderPayment", b =>
                {
                    b.HasOne("OMF.OrderManagementService.Command.Repository.DataContext.TblFoodOrder", "TblFoodOrder")
                        .WithMany("TblOrderPayment")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_tblOrderPayment_tblFoodOrderID")
                        .IsRequired();

                    b.HasOne("OMF.OrderManagementService.Command.Repository.DataContext.TblTableBooking", "TblTableBooking")
                        .WithMany("TblOrderPayment")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_tblOrderPayment_tblTableBookingID")
                        .IsRequired();

                    b.HasOne("OMF.OrderManagementService.Command.Repository.DataContext.TblFoodOrder", null)
                        .WithMany("TblOrderPayments")
                        .HasForeignKey("TblFoodOrderId");

                    b.HasOne("OMF.OrderManagementService.Command.Repository.DataContext.TblTableBooking", null)
                        .WithMany("TblOrderPayments")
                        .HasForeignKey("TblTableBookingId1");
                });

            modelBuilder.Entity("OMF.OrderManagementService.Command.Repository.DataContext.TblTableDetail", b =>
                {
                    b.HasOne("OMF.OrderManagementService.Command.Repository.DataContext.TblTableBooking", "TblTableBooking")
                        .WithMany("TblTableDetail")
                        .HasForeignKey("TblTableBookingId")
                        .HasConstraintName("FK_tblTableOrderMapping_tblTableOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
