// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OMF.RestaurantService.Query.Repository.DataContext;

namespace OMF.RestaurantService.Query.Repository.Migrations
{
    [DbContext(typeof(RestaurantManagementContext))]
    [Migration("20200527070918_restaurant")]
    partial class restaurant
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OMF.RestaurantService.Query.Repository.DataContext.TblCuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(225)")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(225);

                    b.Property<DateTime>("RecordTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordTimeStampCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserCreated")
                        .HasColumnType("int");

                    b.Property<int>("UserModified")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblCuisine");
                });

            modelBuilder.Entity("OMF.RestaurantService.Query.Repository.DataContext.TblLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("RecordTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordTimeStampCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserCreated")
                        .HasColumnType("int");

                    b.Property<int>("UserModified")
                        .HasColumnType("int");

                    b.Property<decimal?>("X")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Y")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Id");

                    b.HasIndex("X")
                        .IsUnique()
                        .HasName("UQ__tblLocat__3BD0198414754610")
                        .HasFilter("[X] IS NOT NULL");

                    b.HasIndex("Y")
                        .IsUnique()
                        .HasName("UQ__tblLocat__3BD01987EC697B94")
                        .HasFilter("[Y] IS NOT NULL");

                    b.ToTable("tblLocation");
                });

            modelBuilder.Entity("OMF.RestaurantService.Query.Repository.DataContext.TblMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(225)")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(225);

                    b.Property<DateTime>("RecordTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordTimeStampCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("TblCuisineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblCuisineID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("UserCreated")
                        .HasColumnType("int");

                    b.Property<int>("UserModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Quantity")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Id");

                    b.HasIndex("TblCuisineId");

                    b.ToTable("tblMenu");
                });

            modelBuilder.Entity("OMF.RestaurantService.Query.Repository.DataContext.TblOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("FromDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("RecordTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordTimeStampCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TblMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblMenuID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TblRestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblRestaurantID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ToDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("UserCreated")
                        .HasColumnType("int");

                    b.Property<int>("UserModified")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TblMenuId");

                    b.HasIndex("TblRestaurantId");

                    b.ToTable("tblOffer");
                });

            modelBuilder.Entity("OMF.RestaurantService.Query.Repository.DataContext.TblRestaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CloseTime")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(5);

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreatedRecordTimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ModifiedTimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(225)")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(225);

                    b.Property<string>("OpeningTime")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(5);

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<int>("TblLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblLocationID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Website")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(225)")
                        .HasDefaultValueSql("('')")
                        .HasMaxLength(225);

                    b.HasKey("Id");

                    b.HasIndex("TblLocationId");

                    b.ToTable("tblRestaurant");
                });

            modelBuilder.Entity("OMF.RestaurantService.Query.Repository.DataContext.TblRestaurantDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedRecordTimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime>("ModifiedTimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TableCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TableCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("TblRestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tblRestaurantID")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("UserCreated")
                        .HasColumnType("int");

                    b.Property<int>("UserModified")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TblRestaurantId");

                    b.ToTable("tblRestaurantDetails");
                });

            modelBuilder.Entity("OMF.RestaurantService.Query.Repository.DataContext.TblMenu", b =>
                {
                    b.HasOne("OMF.RestaurantService.Query.Repository.DataContext.TblCuisine", "TblCuisine")
                        .WithMany("TblMenu")
                        .HasForeignKey("TblCuisineId")
                        .HasConstraintName("FK_tblMenu_tblCuisineID")
                        .IsRequired();
                });

            modelBuilder.Entity("OMF.RestaurantService.Query.Repository.DataContext.TblOffer", b =>
                {
                    b.HasOne("OMF.RestaurantService.Query.Repository.DataContext.TblMenu", "TblMenu")
                        .WithMany("TblOffer")
                        .HasForeignKey("TblMenuId")
                        .HasConstraintName("FK_tblOffer_tblMenuID")
                        .IsRequired();

                    b.HasOne("OMF.RestaurantService.Query.Repository.DataContext.TblRestaurant", "TblRestaurant")
                        .WithMany("TblOffer")
                        .HasForeignKey("TblRestaurantId")
                        .HasConstraintName("FK_tblOffer_tblRestaurantID")
                        .IsRequired();
                });

            modelBuilder.Entity("OMF.RestaurantService.Query.Repository.DataContext.TblRestaurant", b =>
                {
                    b.HasOne("OMF.RestaurantService.Query.Repository.DataContext.TblLocation", "TblLocation")
                        .WithMany("TblRestaurant")
                        .HasForeignKey("TblLocationId")
                        .HasConstraintName("FK_tblRestaurant_tblLocationID")
                        .IsRequired();
                });

            modelBuilder.Entity("OMF.RestaurantService.Query.Repository.DataContext.TblRestaurantDetails", b =>
                {
                    b.HasOne("OMF.RestaurantService.Query.Repository.DataContext.TblRestaurant", "TblRestaurant")
                        .WithMany("TblRestaurantDetails")
                        .HasForeignKey("TblRestaurantId")
                        .HasConstraintName("FK_tblRestaurantDetails_tblRestaurantID")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
